# Generated by Django 5.1.7 on 2025-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Điện - Đồ điện tử'), ('fishing', 'Đồ câu'), ('stationery', 'Đồ dùng học tập'), ('lego', 'Đồ chơi LEGO')], default='electronics', max_length=50),
        ),
    ]
