# Generated by Django 5.1.7 on 2025-03-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_category'),
    ]

    operations = [
    ]
