# Generated by Django 5.1.7 on 2025-03-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
