# Generated by Django 5.1.7 on 2025-03-26 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_product_stock'),
    ]

    operations = [
    ]
